spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/evalart_reto
    username: root
    password: local
    driver-class-name: org.mariadb.jdbc.Driver
application:
  rest:
    client:
      evalart-app:
        url-base: https://test.evalartapp.com/
        connection-timeout: 30
        read-timeout: 30
        path:
          code-decrypt: extapiquest/code_decrypt/{code-encrypt}
